---
- name: Install rpi-eeprom
  ansible.builtin.apt:
    name: rpi-eeprom
    state: latest

- name: Check to see if a reboot is needed
  ansible.builtin.command: rpi-eeprom-update
  register: update_check

- name: Reboot if rpi-eeprom is ready to update
  ansible.builtin.reboot:
  when: "'update required' in update_check.stdout"
